### ISSUE TITLE
Installation Documentation Missing

### ISSUE THREAD

**Issue by macropin** [Huawei/containerops#519]
How is this built and installed?

**Comment by genedna** [comment]
@macropin I am working on an operation tool named [Singular](https://github.com/Huawei/containerops/singular). Because the ContainerOps depends on Kubernetes, so our tool includes installing Kubernetes.  [Singular](https://github.com/Huawei/containerops/singular) also install other distribute projects like [TiDB](http://github.com/pingcap/tidb)/[TiKV](https://github.com/pingcap/tikv), [Nats](http://nats.io). When the [Singular](https://github.com/Huawei/containerops/singular) working, we will update the documents.

Now the [Singular](https://github.com/Huawei/containerops/singular) already ready for install Kubernetes in the DigitalOcean.

**Comment by zoidbergwill** [comment]
I think those Singular links should be https://github.com/Huawei/containerops/tree/master/singular

**Comment by genedna** [comment]
@zoidbergwill Thanks, I updated my comment.
