### ISSUE TITLE
containerops.sh down

### ISSUE THREAD

**Issue by macropin** [Huawei/containerops#520]
containerops.sh is down. DNS does not resolve.

**Comment by genedna** [comment]
I closed the **containerops.sh** for now because no time to sync the newest changelog to site. I will release a service for open source projects build with ContainerOps. It includes [container build](https://github.com/Huawei/containerops/tree/master/assembling), [container image and artifact repository](https://github.com/Huawei/containerops/tree/master/dockyard), [DevOps orchestration engine](https://github.com/Huawei/containerops/tree/master/pilotage).
