### ISSUE TITLE
Could you test k8s1.7.5 + istio 0.2

### ISSUE THREAD

**Issue by johnzheng1975** [Huawei/containerops#641]
We are using tectonic 1.7.5, which will install k8s 1.7.5.
Could you test istio 0.2, see whether it works fine. 

Thanks a lot.

My mail: john.zheng@hp.com

**Comment by fivestarsky** [comment]
Hi, john, we've tested using singular to deploy a k8s 1.7.8 cluster with coreDNS configured, and all the istio 0.2.7 tasks work great.
The entire istio deployment and testing process went smoothly. But we need some time to fully support istio. Did you have any problems using the tool?

**Comment by johnzheng1975** [comment]
Thanks a lot.
We will try early Nov. I will update my test results.

**Comment by johnzheng1975** [comment]
We had tried istio0.5.1, it works well so far.

**Comment by johnzheng1975** [comment]
Do you find issue before: upstream connect error or disconnect/reset before head
It raise both on istio0.5.1 and istio0.7.1.
Here is issue I submitted: https://github.com/istio/istio/issues/4999

**Comment by shaunos** [comment]
this is not a istio issue. it is your infrastructure issue.
recently i came across the same problem. i deploy istio 0.8.0 on openshift origin 3.9 platform.
if you deploy istio in a separate namespace, for example, istio-system, and deploy bookinfo in another namespace, such as demo, and if you use multi-tenant network,   the problem occurs. because your caas-platform isolated the network communication for each namespace.  i, use calico network plugin, these no problem, when i use ovs-multi-tenant network plugin, the same problem occurs. then, i run
 oadm pod-network make-projects-global istio-system, the problem resolved.
